// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/EvidenceEvent.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs).
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class EvidenceEvent
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("event_type")]
        public string EventType { get; set; }

        [JsonProperty("occurred_at")]
        public string OccurredAt { get; set; }

        [JsonProperty("session_id")]
        public string SessionId { get; set; }

        [JsonProperty("entity")]
        public Dictionary<string, object> Entity { get; set; }

        [JsonProperty("observation")]
        public Dictionary<string, object> Observation { get; set; }

        [JsonProperty("place")]
        public Dictionary<string, object> Place { get; set; }

        // enum: observed | inferred | consolidated | probable | remembered
        [JsonProperty("truth_level")]
        public string TruthLevel { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }

        [JsonProperty("evidence")]
        public List<Dictionary<string, object>> Evidence { get; set; }

        [JsonProperty("provenance")]
        public Dictionary<string, object> Provenance { get; set; }
    }
}
