// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/FrameEnvelope.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs).
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class FrameEnvelope
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("session_id")]
        public string SessionId { get; set; }

        [JsonProperty("frame_id")]
        public string FrameId { get; set; }

        [JsonProperty("capture_monotonic_ns")]
        public long CaptureMonotonicNs { get; set; }

        [JsonProperty("captured_at_utc")]
        public string CapturedAtUtc { get; set; }

        [JsonProperty("pose")]
        public Pose Pose { get; set; }

        // default: True
        [JsonProperty("pose_valid")]
        public bool PoseValid { get; set; }

        [JsonProperty("intrinsics")]
        public Dictionary<string, object> Intrinsics { get; set; }

        // enum: 0 | 90 | 180 | 270; default: 0
        [JsonProperty("rotation")]
        public long Rotation { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }
    }

    public sealed class Pose
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("position")]
        public List<double> Position { get; set; }

        [JsonProperty("rotation")]
        public List<double> Rotation { get; set; }
    }
}
