// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/LocalTrack.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs).
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class LocalTrack
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("session_id")]
        public string SessionId { get; set; }

        [JsonProperty("track_id")]
        public string TrackId { get; set; }

        [JsonProperty("source_frame_id")]
        public string SourceFrameId { get; set; }

        [JsonProperty("kind")]
        public string Kind { get; set; }

        [JsonProperty("bbox_or_mask")]
        public Dictionary<string, object> BboxOrMask { get; set; }

        [JsonProperty("velocity_screen")]
        public List<double> VelocityScreen { get; set; }

        [JsonProperty("visibility")]
        public double Visibility { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }

        [JsonProperty("observed_at_monotonic_ns")]
        public long ObservedAtMonotonicNs { get; set; }
    }
}
