// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/ReflexEvent.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs).
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class ReflexEvent
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("session_id")]
        public string SessionId { get; set; }

        [JsonProperty("source_frame_id")]
        public string SourceFrameId { get; set; }

        [JsonProperty("skill")]
        public string Skill { get; set; }

        [JsonProperty("prediction")]
        public Dictionary<string, object> Prediction { get; set; }

        [JsonProperty("horizon_ms")]
        public long HorizonMs { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }

        [JsonProperty("severity")]
        public string Severity { get; set; }

        [JsonProperty("evidence_refs")]
        public List<string> EvidenceRefs { get; set; }

        [JsonProperty("aggregate_key")]
        public string AggregateKey { get; set; }
    }
}
