// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/SceneDelta.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs).
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class SceneDelta
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("session_id")]
        public string SessionId { get; set; }

        [JsonProperty("source_frame_id")]
        public string SourceFrameId { get; set; }

        [JsonProperty("entities")]
        public List<Dictionary<string, object>> Entities { get; set; }

        [JsonProperty("relations")]
        public List<Dictionary<string, object>> Relations { get; set; }

        [JsonProperty("changes")]
        public List<Dictionary<string, object>> Changes { get; set; }

        [JsonProperty("frame_width")]
        public long? FrameWidth { get; set; }

        [JsonProperty("frame_height")]
        public long? FrameHeight { get; set; }

        // enum: 0 | 90 | 180 | 270; default: 0
        [JsonProperty("rotation")]
        public long Rotation { get; set; }

        // default: False
        [JsonProperty("mirrored")]
        public bool Mirrored { get; set; }

        // default: detector_pixels
        [JsonProperty("coordinate_space")]
        public string CoordinateSpace { get; set; }

        // default: 0.0
        [JsonProperty("map_quality")]
        public double MapQuality { get; set; }

        [JsonProperty("evidence_refs")]
        public List<string> EvidenceRefs { get; set; }

        [JsonProperty("expires_at")]
        public string ExpiresAt { get; set; }
    }
}
