// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/UIIntent.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs).
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class UIIntent
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("ui_intent_id")]
        public string UiIntentId { get; set; }

        // enum: ultralive | visionrt | brainlive
        [JsonProperty("producer")]
        public string Producer { get; set; }

        [JsonProperty("source_frame_id")]
        public string SourceFrameId { get; set; }

        [JsonProperty("target_track_id")]
        public string TargetTrackId { get; set; }

        [JsonProperty("entity_id")]
        public string EntityId { get; set; }

        [JsonProperty("component")]
        public string Component { get; set; }

        [JsonProperty("anchor")]
        public Dictionary<string, object> Anchor { get; set; }

        [JsonProperty("content")]
        public Dictionary<string, object> Content { get; set; }

        // enum: observed | probable | remembered | inferred | replay
        [JsonProperty("truth_level")]
        public string TruthLevel { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }

        [JsonProperty("priority")]
        public double Priority { get; set; }

        [JsonProperty("ttl_ms")]
        public long TtlMs { get; set; }

        [JsonProperty("ui_hint")]
        public Dictionary<string, object> UiHint { get; set; }

        [JsonProperty("evidence_refs")]
        public List<string> EvidenceRefs { get; set; }

        [JsonProperty("delivery_id")]
        public string DeliveryId { get; set; }
    }
}
