// <auto-generated>
// SYNCHRONISED COPY from packages/contracts/csharp/UIReceipt.cs — DO NOT EDIT BY HAND.
// Regenerate with the Unity menu "MLOmega/Contracts/Sync from repo" (Editor/SyncContracts.cs).
// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).
// </auto-generated>
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MLOmega.Contracts.V19
{
    public sealed class UIReceipt
    {
        // default: v19.0
        [JsonProperty("contracts_version")]
        public string ContractsVersion { get; set; }

        [JsonProperty("ui_intent_id")]
        public string UiIntentId { get; set; }

        [JsonProperty("delivery_id")]
        public string DeliveryId { get; set; }

        // enum: displayed | seen | acted | dismissed | corrected
        [JsonProperty("event")]
        public string Event { get; set; }

        [JsonProperty("observed_at")]
        public string ObservedAt { get; set; }

        [JsonProperty("local_track_state")]
        public Dictionary<string, object> LocalTrackState { get; set; }

        [JsonProperty("user_action")]
        public Dictionary<string, object> UserAction { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }
    }
}
