// MLOmega V19 — E23
// Editor tool that re-syncs the Unity copies of the V19 contracts from the repo
// source of truth (packages/contracts/csharp/*.cs) into Assets/Scripts/Contracts/.
//
// Why a transform and not a raw copy:
//   The generated repo POCOs target System.Text.Json (which Unity does not ship)
//   and use a C# 10 file-scoped namespace. Unity 6 serializes via the official
//   com.unity.nuget.newtonsoft-json package, so this tool rewrites:
//     - `using System.Text.Json.Serialization;` -> `using Newtonsoft.Json;`
//     - `[JsonPropertyName("x")]`               -> `[JsonProperty("x")]`
//     - file-scoped `namespace X;`              -> block-scoped `namespace X { ... }`
//   It also drops the duplicate nested `ReflexEvent` class embedded in
//   HotSceneContext.cs (ReflexEvent.cs already provides the canonical one), and
//   prepends a "synchronised copy — do not edit by hand" header to each file.
//
// This mirrors exactly the hand-checked copies committed alongside it, so a fresh
// run produces byte-identical output and the copies stay verifiably in sync.
using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace MLOmega.XR.Editor
{
    public static class SyncContracts
    {
        // Relative to the Unity project root (apps/xr-mobile). Four levels up is
        // the monorepo root; from there the generated C# contracts live under
        // packages/contracts/csharp.
        private const string RepoRelativeSource = "../../packages/contracts/csharp";
        private const string DestRelativeToAssets = "Scripts/Contracts";

        [MenuItem("MLOmega/Contracts/Sync from repo")]
        public static void Sync()
        {
            string projectRoot = Directory.GetParent(Application.dataPath)!.FullName;
            string source = Path.GetFullPath(Path.Combine(projectRoot, RepoRelativeSource));
            string dest = Path.Combine(Application.dataPath, DestRelativeToAssets);

            if (!Directory.Exists(source))
            {
                EditorUtility.DisplayDialog(
                    "Sync contracts",
                    $"Source folder not found:\n{source}\n\n" +
                    "Run this from a checkout of the full monorepo (packages/contracts/csharp must exist).",
                    "OK");
                return;
            }

            Directory.CreateDirectory(dest);
            int count = 0;
            foreach (string src in Directory.GetFiles(source, "*.cs"))
            {
                string name = Path.GetFileName(src);
                string transformed = Transform(File.ReadAllText(src), name);
                File.WriteAllText(Path.Combine(dest, name), transformed, new UTF8Encoding(false));
                count++;
            }

            AssetDatabase.Refresh();
            Debug.Log($"[SyncContracts] Synced {count} contract file(s) from {source} -> {dest}.");
            EditorUtility.DisplayDialog("Sync contracts",
                $"Synced {count} contract file(s) into Assets/{DestRelativeToAssets}.", "OK");
        }

        internal static string Transform(string sourceText, string fileName)
        {
            string text = sourceText;

            // 1. Swap the JSON library.
            text = text.Replace(
                "using System.Text.Json.Serialization;",
                "using Newtonsoft.Json;");
            text = Regex.Replace(text, @"\[JsonPropertyName\(", "[JsonProperty(");

            // 2. Drop the duplicate ReflexEvent nested class in HotSceneContext.cs.
            if (fileName.Equals("HotSceneContext.cs", StringComparison.OrdinalIgnoreCase))
            {
                text = RemoveDuplicateReflexEvent(text);
            }

            // 3. File-scoped namespace -> block-scoped namespace.
            //    `namespace MLOmega.Contracts.V19;` becomes `namespace ... { <body> }`.
            var nsMatch = Regex.Match(text, @"namespace\s+([\w\.]+)\s*;\s*\n");
            if (nsMatch.Success)
            {
                string ns = nsMatch.Groups[1].Value;
                int bodyStart = nsMatch.Index + nsMatch.Length;
                string head = text.Substring(0, nsMatch.Index);
                string body = text.Substring(bodyStart).TrimEnd() + "\n";
                string indentedBody = IndentBlock(body);
                text = head + $"namespace {ns}\n{{\n{indentedBody}}}\n";
            }

            // 4. Header note.
            string header =
                "// <auto-generated>\n" +
                $"// SYNCHRONISED COPY from packages/contracts/csharp/{fileName} — DO NOT EDIT BY HAND.\n" +
                "// Regenerate with the Unity menu \"MLOmega/Contracts/Sync from repo\" (Editor/SyncContracts.cs).\n" +
                "// Source of truth: packages/contracts/csharp (generated from packages/contracts/schemas/*.schema.json).\n" +
                "// </auto-generated>\n";
            // Replace the original <auto-generated> block if present, otherwise prepend.
            text = Regex.Replace(text,
                @"^// <auto-generated>.*?// </auto-generated>\n",
                header, RegexOptions.Singleline);
            if (!text.StartsWith("// <auto-generated>"))
            {
                text = header + text;
            }

            return text;
        }

        private static string RemoveDuplicateReflexEvent(string text)
        {
            // The nested ReflexEvent is the LAST class in the source file; strip
            // everything from the blank line before "public sealed class ReflexEvent"
            // to the end of that class, keeping the enclosing namespace body intact.
            int idx = text.IndexOf("public sealed class ReflexEvent", StringComparison.Ordinal);
            if (idx < 0)
            {
                return text;
            }
            // Back up over any preceding blank line.
            int cut = idx;
            while (cut > 0 && (text[cut - 1] == ' ' || text[cut - 1] == '\n' || text[cut - 1] == '\r'))
            {
                cut--;
            }
            return text.Substring(0, cut) + "\n";
        }

        private static string IndentBlock(string body)
        {
            var sb = new StringBuilder(body.Length + 64);
            foreach (string line in body.Split('\n'))
            {
                if (line.Length == 0)
                {
                    sb.Append('\n');
                }
                else
                {
                    sb.Append("    ").Append(line).Append('\n');
                }
            }
            return sb.ToString();
        }
    }
}
